// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarGarageManager.Migrations
{
    [DbContext(typeof(CarGarageManagerContext))]
    partial class CarGarageManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarGarageManager.Models.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarBrandID");

                    b.Property<int>("CarModelFK");

                    b.Property<int>("Mileage");

                    b.Property<int>("Price");

                    b.Property<int>("Year");

                    b.HasKey("CarID");

                    b.HasIndex("CarBrandID");

                    b.HasIndex("CarModelFK");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("CarGarageManager.Models.CarBrand", b =>
                {
                    b.Property<int>("CarBrandID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarBrandName");

                    b.HasKey("CarBrandID");

                    b.ToTable("CarBrand");
                });

            modelBuilder.Entity("CarGarageManager.Models.CarModel", b =>
                {
                    b.Property<int>("CarModelID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarBrandFK");

                    b.Property<string>("CarModelName");

                    b.HasKey("CarModelID");

                    b.HasIndex("CarBrandFK");

                    b.ToTable("CarModel");
                });

            modelBuilder.Entity("CarGarageManager.Models.Car", b =>
                {
                    b.HasOne("CarGarageManager.Models.CarBrand")
                        .WithMany("Cars")
                        .HasForeignKey("CarBrandID");

                    b.HasOne("CarGarageManager.Models.CarModel", "CarModel")
                        .WithMany("Cars")
                        .HasForeignKey("CarModelFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CarGarageManager.Models.CarModel", b =>
                {
                    b.HasOne("CarGarageManager.Models.CarBrand", "CarBrand")
                        .WithMany()
                        .HasForeignKey("CarBrandFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
